### PR TITLE
Reduce Docker image size. resolves #269

### LINKED ISSUE #269: Reduce Docker image size
Wallabag Docker image size **uncompressed** is 574 MB
According to [dive](https://github.com/wagoodman/dive) the image can be reduced at least in 100 MB.

I have some ideas but I'm not expert in php/composer:
* Why do you install Python and Python libraries? It takes ~188MB
* Remove `/root/composer/` I think this is the composer cache ~43 MB
* Remove `.git` folder (repository history) in the final image. I think it will be wise to remove all but the php source code and config.
* Is it possible to uninstall composer and other dependencies after the installation is complete? (I think you only need php, php-libs and nginx)
* Vendor folder is ~104MB. Are all dependencies required?

Update: If you don't agree, another alternative is to publish 2 images (with different tags). I think the slim image could be 1/3 the size of the current image with the same features (redis). Some of us are running Wallabag in RaspberryPi with low resources. :)

### PR DESCRIPTION
**Pull request by ngosang**
Size (uncompressed): Previous 573.1 MB  /  This PR 225.8 MB
Container startup time is faster. Ansible and chown were slow
Build time is 3 times faster. Less packages and TAR download
No changes required by the user. Same env vars, same paths, same core packages ...

* Update Alpine 3.16. gnu-libiconv is already fixed in this version
* Update PHP 8
* Remove heavy packages: ansible, git, make, bash ...
* Download Wallabag TAR. Is faster and git is not required
* Replace environment variables with envsubst
* Reorder steps to build faster and reduce image size

### CODE REVIEW

**Comment by ngosang** [comment]
I'm using this in Production in combination with #265
I don't know how to test import and migration tasks. They should work but maybe it's neccessary to install bash and make. They are commented in the PR for that reason.

**Comment by luckydonald** [comment]
Is this already available on docker hub somewhere?

**Comment by ngosang** [comment]
> Is this already available on docker hub somewhere?

No sorry, but you can download the PR and build the image in your server:
`docker build -t wallabag:custom .`

**Comment by ngosang** [comment]
I don't know if anyone is using this image but me. I just pushed a commit with Wallabag 2.5.1 + Alpine 3.16 + PHP 8

**Comment by ngosang** [comment]
@j0k3r I'm using a custom Docker image but I'm interested in merge upstream. If you are willing to merge I can split this PR into smaller PRs. Also tell me if some changes in this PR are not going to be accepted (like using Alpine or Nginx..)

**Comment by ngosang** [comment]
Already fixed in other PRs

**Pull request closed without merging**
