### PR TITLE
create sqlite database file if it does not exist

### PR DESCRIPTION
**Pull request by fho**
When a volume mount is used for /var/wwww/wallabag/data, as documented[^1], the container fails to start with the error messages:

    wc: /var/www/wallabag/data/db/wallabag.sqlite: No such file or directory
    Configuring the SQLite database ...
    In ExceptionConverter.php line 76:
      An exception occurred in the driver: SQLSTATE[HY000] [14] unable to
      open database file
    [..]

In the volume mount the db directory and the empty db/wallabag.sqlite do not exist which causes the issue.

Check in the entrypoint script if the file exist, if it does not create the db directory and the file and make nobody the owner.

This fixes: https://github.com/wallabag/docker/issues/316

[^1]:https://github.com/wallabag/docker/tree/96dd9bc3e3d12b216471db03f5afacd6d1afac61#sqlite

### CODE REVIEW

**Comment by fho** [comment]
A docker image containing the fix can be found here: https://github.com/fho/wallabag-docker/pkgs/container/wallabag. It will only be temporarily available.

**Comment by itsamenathan** [comment]
+1 as I just ran into this issue

**Comment by The-Loki-Project** [comment]
+1 ran into this issue, would love for it be fixed

**Comment by fho** [comment]
@Kdecherf @j0k3r @nicosomb could you please provide feedback or even better merge this PR?

**Comment by Kdecherf** [comment]
Hello @fho,

I finally took time to check on this issue, and I worked on a slightly different fix here #402

**Comment by fho** [comment]
@Kdecherf thanks for merging a fix

**Pull request closed without merging**
