### PR TITLE
Initiate testing with Travis

### PR DESCRIPTION
**Pull request by j0k3r**
:construction:

### CODE REVIEW

**Comment by j0k3r** [comment]
It looks ok but we only run the build on SQLite.
I don't know how to launch the test suite with each database available.
If anyone got an idea.

**Comment by xsteadfastx** [comment]
oh thats cool. i never thought this is possible with travis. maybe its possible with the other containers... let me think about this. we could just write a docker-compose.... or one for each db... fire it up and see if we can reach the front page with curl.

**Comment by xsteadfastx** [comment]
i used your PR and added some more stuff... its in the master branch. any thoughts?

**Comment by j0k3r** [comment]
So you push stuff on the master branch and then ask for feedback? This isn't the way it should works.
PR are here to propose change to be validated by everyone. Especially if you aren't sure about the solution. That's why I opened a PR about Travis.

**Comment by xsteadfastx** [comment]
thats true. sorry. that was not a good way to go for.

**Pull request closed without merging**
