### PR TITLE
2.3.6

### PR DESCRIPTION
**Pull request by j0k3r**
See https://github.com/wallabag/wallabag/pull/3836

### CODE REVIEW

**Comment by noplanman** [comment]
@j0k3r When will the new version be on docker hub?
Just wondering about the release procedure.

**Comment by j0k3r** [comment]
@xsteadfastx any idea?

**Comment by nsteinmetz** [comment]
Hi,

Any news on this ?

**Comment by j0k3r** [comment]
https://github.com/wallabag/docker/issues/144#issuecomment-467432977

**Pull request merged**
