### PR TITLE
Update Alpine 3.17 and PHP 8.1

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Review by j0k3r — COMMENTED** [review]
Why jumping to PHP 8.1?
The upcomding 2.6.0 version will drop PHP < 8.0, so we need to keep 8.0.
https://github.com/wallabag/wallabag/issues/6052

**Comment by ngosang** [comment]
It's important to keep the software updated. PHP 8.1 is the latest stable release and it provides big improvements in performance. https://www.php.net/releases/8.1/en.php#performance_improvements
* Wallabag should be compatible with all versions of PHP with support 8.0 & 8.1. PHP 8.0 is not in active development since few days ago => https://www.php.net/supported-versions.php
* This repository is to build and test the best Docker image for Wallabag. Docker isolates the packages from the packages installed in the host. There is not reason to package an old version.
* This repository is not for testing PHP 8.0 or other PHP versions. You are already testing PHP 8.1 in the Wallabag repository and the CI/CD actions are passing. https://github.com/wallabag/wallabag/pull/6102

**Comment by j0k3r** [comment]
@ngosang good points! 👍

**Review by j0k3r — APPROVED** [review]

**Comment by ngosang** [comment]
@j0k3r Why do you maintain a different Docker files here? https://github.com/wallabag/wallabag/tree/master/docker
How I can help to merge/simplify both?

**Comment by Kdecherf** [comment]
@ngosang the Dockerfile in the main wallabag repository is used for development purpose

**Pull request merged**
