### PR TITLE
Updated image to wallabag 2.3.0

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by nicosomb** [comment]
You're right about SQLite. 

About docker-compose, I'll a PR after this one. Some users asked me the new image for 2.3.0, I want to release it quick (and maybe dirty). 
Do you have any idea why the test fails on PG? I think that the install with pg fails, I will have a look.

**Comment by xsteadfastx** [comment]
it gets a 500... that means that the pg init doesnt worked right.

**Comment by nicosomb** [comment]
Yes, I saw that ;-) I need to see why it fails. Will try to install locally.

**Comment by nicosomb** [comment]
> [localhost] TASK [add postgresql user] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var An exception occurred during task execution. To see the full traceback, use -vvv. The error was: HINT: Remove UNENCRYPTED to store the password in encrypted form instead. fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_U955zc/ansible_module_postgresql_user.py\", line 773, in <module>\n main()\n File \"/tmp/ansible_U955zc/ansible_module_postgresql_user.py\", line 732, in main\n changed = user_add(cursor, user, password, role_attr_flags, encrypted, expires)\n File \"/tmp/ansible_U955zc/ansible_module_postgresql_user.py\", line 260, in user_add\n cursor.execute(query, query_password_data)\n File \"/usr/lib/python2.7/site-packages/psycopg2/extras.py\", line 144, in execute\n return super(DictCursor, self).execute(query, vars)\npsycopg2.NotSupportedError: UNENCRYPTED PASSWORD is no longer supported\nLINE 1: CREATE USER \"wallabag\" WITH UNENCRYPTED PASSWORD 'wallapass'...\n ^\nHINT: Remove UNENCRYPTED to store the password in encrypted form instead.\n\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0} RUNNING HANDLER [run install] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var RUNNING HANDLER

**Comment by nicosomb** [comment]
See https://github.com/ansible/ansible/issues/25823

**Comment by nicosomb** [comment]
I will force to postgres 9.6.

**Pull request merged**
