### PR TITLE
Update Alpine 3.16

### PR DESCRIPTION
**Pull request by ngosang**
Related #269 #270

### CODE REVIEW

**Review by j0k3r — COMMENTED** [review]
I already tried :)
https://github.com/wallabag/docker/commit/bce0488aed738caac0b1d0eb8cc21a5ebdbd5dd4

**Comment by ngosang** [comment]
@j0k3r I tested it in local and the CI/CD checks passed.

**Review by j0k3r — APPROVED** [review]
OH ok it now passes 🤔

**Comment by Kdecherf** [comment]
I'm wondering if we have a working test to ensure that there's no regression on iconv-related functions @j0k3r

**Comment by j0k3r** [comment]
Tests are pretty basic, we login and check if some pages are ok

**Comment by ngosang** [comment]
Related #306

**Pull request merged**
