### PR TITLE
Allow for file-based environment variables

### PR DESCRIPTION
**Pull request by dotdev**
Allows for file content to be set as the environment variable.
Useful for e.g. docker secrets were the secret is mounted as a file in /run/secrets/{filename}

### CODE REVIEW

**Comment by xsteadfastx** [comment]
couldnt you just solve it with a env file?

**Comment by dotdev** [comment]
The advantage of using the docker secrets is that the secret itself is never stored on disk in plain text.
It's stored encrypted on the docker swarm, and only exposed to the container that is given access.
It makes it easier to version control an entire stack (not having the secrets in plain text in an env file) and adds an extra layer of abstraction between the container and the secret; whereas using an env file would mean that the env file should be available on all swarm nodes.

**Comment by Kdecherf** [comment]
Hello @dotdev,

We've removed support of Ansible for provisioning configuration. Would you like to rebase your PR or close it?

**Comment by dotdev** [comment]
Hi @Kdecherf ,

It's been a while, and I no longer am in need for this. I'll close this PR

**Pull request closed without merging**
